version: '3'
services:
  spring-discovery-srv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_TO_DEPLOY: ./build/libs/spring-discovery-srv.jar
        JAR_TO_DEPLOY_FINAL_NAME: spring-discovery-srv.jar
    image: ${IMAGE:-dedsclocaltest}
    env_file:
      - config/envProperties-${ENV:-local}.env      
